"""convert_price_history_to_utc

Revision ID: 02e01979bf25
Revises: 0f80c6c72d26
Create Date: 2026-09-30 13:40:01.548582

"""
"""convert_price_history_to_utc

Revision ID: <auto-generated>
Revises: 0f80c6c72d26
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from datetime import timezone
from zoneinfo import ZoneInfo

TABLE_NAME = 'item_price_history' 
COLUMN_NAME = 'created_at' 

revision = '02e01979bf25'
down_revision = '0f80c6c72d26'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Bind to the active database connection
    bind = op.get_bind()
    session = Session(bind=bind)

    # Reflect the price history table properties
    metadata = sa.MetaData()
    target_table = sa.Table(TABLE_NAME, metadata, autoload_with=bind)

    # 2. Fetch all rows with their naive Pacific timestamps
    records = session.execute(
        sa.select(target_table.c.id, getattr(target_table.c, COLUMN_NAME))
    ).all()
    
    pacific_tz = ZoneInfo("America/Los_Angeles")

    # 3. Loop through and shift every row +7 or +8 hours to UTC
    for record_id, naive_pacific_dt in records:
        if naive_pacific_dt is not None:
            # Tag as Pacific (handles historical daylight savings accurately)
            localized_pacific = naive_pacific_dt.replace(tzinfo=pacific_tz)
            
            # Convert timeline values entirely into UTC
            utc_aware_dt = localized_pacific.astimezone(timezone.utc)
            
            # Save the fixed UTC timestamp down to the row
            session.execute(
                sa.update(target_table)
                .where(target_table.c.id == record_id)
                .values({COLUMN_NAME: utc_aware_dt})
            )
            
    session.commit()

    # 4. Modify column properties to accept timezones going forward
    with op.batch_alter_table(TABLE_NAME, schema=None) as batch_op:
        batch_op.alter_column(COLUMN_NAME,
               existing_type=sa.DateTime(timezone=False),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)


def downgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    metadata = sa.MetaData()
    target_table = sa.Table(TABLE_NAME, metadata, autoload_with=bind)
    records = session.execute(sa.select(target_table.c.id, getattr(target_table.c, COLUMN_NAME))).all()
    pacific_tz = ZoneInfo("America/Los_Angeles")

    for record_id, utc_dt in records:
        if utc_dt is not None:
            if utc_dt.tzinfo is None:
                utc_dt = utc_dt.replace(tzinfo=timezone.utc)
            pacific_dt = utc_dt.astimezone(pacific_tz)
            naive_pacific = pacific_dt.replace(tzinfo=None)
            session.execute(sa.update(target_table).where(target_table.c.id == record_id).values({COLUMN_NAME: naive_pacific}))
    session.commit()

    with op.batch_alter_table(TABLE_NAME, schema=None) as batch_op:
        batch_op.alter_column(COLUMN_NAME,
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(timezone=False),
               existing_nullable=True)
